// backend/src/main/java/com/integrityfamily/domain/AuditEventType.java
package com.integrityfamily.domain;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    LOGOUT,
    SESSION_EXPIRED,
    FAMILY_REGISTERED,
    CLI_COMMAND_EXECUTED,
    EVALUATION_STARTED,
    EVALUATION_SUBMITTED,
    PLAN_TASK_TOGGLED,
    MISSION_COMPLETED,
    SPRINT_CLOSED,
    DAILY_CREATED,
    EVIDENCE_CREATED,
    FAMILY_HOME_ACTION_EXECUTED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    PROFESSIONAL_DRAFT_GENERATED,
    PROFESSIONAL_DRAFT_USED_AS_NOTE
}


